<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Lastname in Thai)_lastname_th</name>
   <tag></tag>
   <elementGuidId>ed71bd83-b63c-4f28-b77c-0bddb5e0dbb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastname_th']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lastname_th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a030d256-416b-4bab-b62a-9b9800263ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5e2db7d-4dac-4d0b-8d47-cd1604f50863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9567c43a-ca02-45cf-a5ac-331d0730ef51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname_th</value>
      <webElementGuid>8d312dcc-2f5a-4741-a6de-3742f55ed094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname_th</value>
      <webElementGuid>a03cf2f2-b0a4-4ecc-93a5-3cca1bcdb784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>นามสกุลเป็นภาษาไทย</value>
      <webElementGuid>786366f2-16d1-4508-a063-e8bb9e3c6f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname_th&quot;)</value>
      <webElementGuid>278c726a-7b62-4c92-a98b-ad0ee8d8bcb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastname_th']</value>
      <webElementGuid>d8e43a7e-d982-412b-a88f-af5dce205d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[7]/input</value>
      <webElementGuid>a9008a18-06a3-4705-aacc-59acb8dd3792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>a788f3c0-6492-494a-b91f-51cd33626737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lastname_th' and @name = 'lastname_th' and @placeholder = 'นามสกุลเป็นภาษาไทย']</value>
      <webElementGuid>a6d68bdf-81ea-4994-b0be-e9eef4c516ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
