<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Title in Thai)_title_th</name>
   <tag></tag>
   <elementGuidId>c1d6927a-69cc-4afd-b2a9-f831ce4a3ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title_th']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title_th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4900b3f4-ac59-40ef-98e4-48132bf5d251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f620bced-bb88-4a33-ac6f-b307caf07f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9fb1d60f-0eb8-4720-8880-e7168223e83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_th</value>
      <webElementGuid>e04c09b7-6991-483a-9ae3-958db166a3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title_th</value>
      <webElementGuid>ffd0de13-30d5-425c-85ed-f68b6a88cce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>คำนำหน้าชื่อเป็นภาษาไทย (เช่น นาย นาง นางสาว) </value>
      <webElementGuid>655aabe5-8802-495e-94a2-02d42ccd4720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_th&quot;)</value>
      <webElementGuid>f09cee17-66d3-4ad2-9f57-836a644cceea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title_th']</value>
      <webElementGuid>6451c284-6763-4c19-b838-9e2bb5f3a15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[5]/input</value>
      <webElementGuid>c32790a4-cc74-4806-bae1-09ae9d32166a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>7f3f291d-e863-4cc3-bd30-2af79e91ed2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'title_th' and @name = 'title_th' and @placeholder = 'คำนำหน้าชื่อเป็นภาษาไทย (เช่น นาย นาง นางสาว) ']</value>
      <webElementGuid>1bff93ee-0020-4044-8f70-2f128743e0cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
