<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Firstname in Thai)_firstname_th</name>
   <tag></tag>
   <elementGuidId>2b939a89-fea5-41fa-8e64-cdfc9f4b0aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstname_th']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#firstname_th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c3b2511-4ec7-46e5-b47a-8607f4bea567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da516eb5-9e17-4c04-a860-d8b3688c3f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a9972759-aecc-42a6-9735-a52a711be70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname_th</value>
      <webElementGuid>872d379f-8ada-4830-8e24-a24b8e3c796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname_th</value>
      <webElementGuid>1127c63f-2538-442f-b159-f553cc960ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ชื่อจริงเป็นภาษาไทย</value>
      <webElementGuid>bd4611ce-fb5b-48e0-9a34-10795372d3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstname_th&quot;)</value>
      <webElementGuid>65dd8660-8936-4037-b2d5-0291173872c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstname_th']</value>
      <webElementGuid>b56242a3-7492-468b-8379-00f57975b13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[6]/input</value>
      <webElementGuid>165e1049-6a60-4f4a-afc6-a256b297de3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>2fc46cb7-4691-4aed-a622-0f3a36d2a69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'firstname_th' and @name = 'firstname_th' and @placeholder = 'ชื่อจริงเป็นภาษาไทย']</value>
      <webElementGuid>31473f6e-628a-4362-97fc-615c935499ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
