<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Lastname in English)_lastname_en</name>
   <tag></tag>
   <elementGuidId>0fb11c22-b080-4641-a8dd-b83dc2341e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastname_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lastname_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c398092d-676d-41cd-b0ae-0ce42954ab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84e42bc4-22e5-425a-b823-5c2de7747f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1cc51ab3-91ea-49ae-8219-b33ad00403c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname_en</value>
      <webElementGuid>b69a9b1d-5294-406e-9501-6e5b5cfb8747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname_en</value>
      <webElementGuid>48a2f88e-e8f0-4492-8133-1a93d98d4892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>นามสกุลเป็นภาษาอังกฤษ</value>
      <webElementGuid>121df826-40d3-43ba-b541-3c2c3fd2b28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname_en&quot;)</value>
      <webElementGuid>4ecf1051-0a20-4a13-9b75-3d4d72ea2da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastname_en']</value>
      <webElementGuid>726ddd48-6954-4791-9a7f-86c4b4a67bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[10]/input</value>
      <webElementGuid>db4611d5-8dba-4b9d-b25e-c4eac35dce6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>70936379-9230-4eb4-8e88-08498aaa1045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lastname_en' and @name = 'lastname_en' and @placeholder = 'นามสกุลเป็นภาษาอังกฤษ']</value>
      <webElementGuid>4fe61168-cba6-4de8-a263-fa434738ffd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
