<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Firstname in English)_firstname_en</name>
   <tag></tag>
   <elementGuidId>0ad60631-a444-4bd2-bbff-4d3f3133490d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstname_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#firstname_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03af75c2-0184-400d-b701-8d243e798372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb9509f3-e9fd-410e-980c-ba739f7c517a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5f9a8b1b-2a35-479e-941d-20868afcdbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname_en</value>
      <webElementGuid>8b939340-8b82-4cac-a6b0-411f64219647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname_en</value>
      <webElementGuid>3119b71c-0274-4ded-8938-861cac2f657c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ชื่อจริงเป็นภาษาอังกฤษ</value>
      <webElementGuid>b64070eb-0ea6-42b9-bf7d-d436a2acfe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstname_en&quot;)</value>
      <webElementGuid>38b45cf5-f419-4ba1-b09c-5a2591531315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstname_en']</value>
      <webElementGuid>9986b7c7-1530-493f-b988-45ac858025cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[9]/input</value>
      <webElementGuid>3753d1a4-ca19-451c-83a5-9f0986d4a994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>e142435f-a4c8-494c-aa82-deda21c796ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'firstname_en' and @name = 'firstname_en' and @placeholder = 'ชื่อจริงเป็นภาษาอังกฤษ']</value>
      <webElementGuid>ccf73279-fa90-48c6-a338-709df922301b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
