<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Title in English)_title_en</name>
   <tag></tag>
   <elementGuidId>edacace4-a75b-4dd5-8a15-f3453054bc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8694a61-6c90-4b90-9b58-f360670b93bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>874cb301-6202-4248-8c4c-9e923e73b8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06b813d0-b671-403e-b0a4-208422d38f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_en</value>
      <webElementGuid>4b07a0b8-f792-4e20-98ef-3f8e562307ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title_en</value>
      <webElementGuid>770bbf29-c399-45fc-be2b-91193e0aba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>คำนำหน้าชื่อเป็นภาษาอังกฤษ (เช่น Mr. Mrs. Ms.)</value>
      <webElementGuid>2ee2b8e4-db2e-4474-850b-69acea7b184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_en&quot;)</value>
      <webElementGuid>2f3f244f-658c-4971-a3c1-198c2de2466b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title_en']</value>
      <webElementGuid>1987698f-b4ab-451a-9a9e-60beb0351236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='cv-common-main']/form/div[8]/input</value>
      <webElementGuid>90e8cb3e-bd3f-42bb-8a62-998a110f2225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>73b2116a-91e6-4135-9dc3-e0e2e4851be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'title_en' and @name = 'title_en' and @placeholder = 'คำนำหน้าชื่อเป็นภาษาอังกฤษ (เช่น Mr. Mrs. Ms.)']</value>
      <webElementGuid>c3e0a583-eb32-473e-aee4-5eb23da3369e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
