<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_telephone</name>
   <tag></tag>
   <elementGuidId>47629252-b0b9-404e-993d-28072d4089cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-telephone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-telephone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52a4e05b-05e8-4c40-9a28-fbc67729a2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>95e416f3-3e2d-49f5-b71f-6e972e14fa24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>b95d9162-17b6-4386-8774-52416fe241da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone / เบอร์โทรศัพท์</value>
      <webElementGuid>01c39fa4-3a0f-4d00-823c-172ff481ee49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-telephone</value>
      <webElementGuid>a0518fda-d042-463b-9ebc-b4c2c00e7afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e5d4a199-66d0-4b71-9941-873e67c20512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-telephone&quot;)</value>
      <webElementGuid>eb95fc36-7e16-4fe7-917b-fd8d0ef8961e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-telephone']</value>
      <webElementGuid>2f1c773a-2e50-4ecb-bfa4-ec6ea362021b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='account']/div[5]/div/input</value>
      <webElementGuid>c251207a-b479-4263-8a51-7bbb650b4e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>73d1b848-a7df-45e7-ab3f-8839d77d238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'telephone' and @placeholder = 'Phone / เบอร์โทรศัพท์' and @id = 'input-telephone']</value>
      <webElementGuid>9e33f7a5-9c31-463e-bd89-d8b342922a36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
